### ISSUE TITLE
Build fails on Solaris/illumos

### ISSUE THREAD

**Issue by ptribble** [minio/minio#17398]
## NOTE

Attempting to build minio server on an illumos platform fails

## Expected Behavior

Clean successful build.

## Current Behavior

```
go install github.com/minio/minio@latest
# github.com/containerd/console
pkg/mod/github.com/containerd/console@v1.0.4-0.20230313162750-1ae8d489ac81/console.go:83:12: undefined: checkConsole
pkg/mod/github.com/containerd/console@v1.0.4-0.20230313162750-1ae8d489ac81/console.go:86:9: undefined: newMaster

```
## Possible Solution

This is caused by the update in #17276 of containerd/console v1.0.3 (which works) to v1.0.4 (which doesn't). A possible solution is to simply revert containerd/console to v1.0.3, while we try and fix upstream in https://github.com/containerd/console/issues/75

## Steps to Reproduce (for bugs)

Attempt to build latest on an illumos or Solaris platform.

## Context

I ship a packaged minio server on illumos.

## Regression

Is this issue a regression? (Yes / No) --> YEs.

Caused by #17276

For confirmation, building RELEASE.2023-05-18T00-05-36Z works fine.

## Your Environment

* Operating System and version (`uname -a`):

illumos/Solaris:
SunOS peter-9020 5.11 tribblix-m30 i86pc i386 i86pc
go version go1.20.5 illumos/amd64

**Comment by klauspost** [comment]
I suspect bubbletea is the source of the dependency:

```
λ go mod why github.com/containerd/console
# github.com/containerd/console
github.com/minio/minio/cmd
github.com/minio/console/restapi
github.com/minio/mc/cmd
github.com/charmbracelet/bubbletea
github.com/containerd/console
```

I think upgrading bubbletea in [mc](https://github.com/minio/mc) when https://github.com/charmbracelet/bubbletea/issues/737 is the way to go.

**Comment by harshavardhana** [comment]
This should be fixed already with upgraded dependencies.

**Comment by xmerlin** [comment]
I've just compiled RELEASE.2023-09-23T03-47-50Z and the problem is not fixed:

../.gopath/pkg/mod/github.com/containerd/console@v1.0.4-0.20230313162750-1ae8d489ac81/console.go:83:12: undefined: checkConsole
../.gopath/pkg/mod/github.com/containerd/console@v1.0.4-0.20230313162750-1ae8d489ac81/console.go:86:9: undefined: newMaster

**Comment by harshavardhana** [comment]
This is not our primary platform and neither a priority. Feel free to send fixes to upstream packages that broke the Solaris support.
