### ISSUE TITLE
Minio web does not load on Safari

### ISSUE THREAD

**Issue by bugs181** [minio/minio#3791]
Fresh install of Minio using `brew` on OS X Yosemite (10.0.10.1). Safari 8.0 (10600.1.25.1). Only getting the spinner on Safari but loads fine on Chrome.

Console only has this error: `TypeError: undefined is not a function (evaluating 'Object.assign({},A)')`

    [Error] TypeError: undefined is not a function (evaluating 'Object.assign({},A)')
        o (index_bundle-2017-02-15T22-41-23Z.js, line 24)
        g (index_bundle-2017-02-15T22-41-23Z.js, line 24)
        (anonymous function) (index_bundle-2017-02-15T22-41-23Z.js, line 28)
        (anonymous function) (index_bundle-2017-02-15T22-41-23Z.js, line 29)
        M (index_bundle-2017-02-15T22-41-23Z.js, line 1)
        (anonymous function) (index_bundle-2017-02-15T22-41-23Z.js, line 1)
        M (index_bundle-2017-02-15T22-41-23Z.js, line 1)
        (anonymous function) (index_bundle-2017-02-15T22-41-23Z.js, line 1)
        global code (index_bundle-2017-02-15T22-41-23Z.js, line 1)

## Expected Behavior

To load the next page (on Chrome, this is credentials like AccessKey and SecretKey

## Current Behavior

Web page just has spinning/loading logo.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Minio version 0.0.0
* Environment name and version (e.g. nginx 1.9.1): Installed with Homebrew >1.1.0 
* Server type and version: 
* Operating System and version: OS X Yosemite (10.0.10.1)
* Link to your project:

**Comment by harshavardhana** [comment]
Can you visit https://play.minio.io:9000/ and validate if it works on Safari @bugs181

**Comment by rushenn** [comment]
Works fine on Sierra 10.12.1/Safari 10.0.1 (12602.2.14.0.7)

**Comment by gitjeff05** [comment]
Object.assign is [not supported in Safari prior to version 9](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility), which was ([released September 30, 2015](https://en.wikipedia.org/wiki/Safari_version_history)). It is also not supported in IE (but is supported on Edge). Looks like Object.assign is referenced in two files: ``browser/app/js/reducers.js`` and ``browser/app/js/components/Browse.js``. Might not be that difficult to add the polyfill if IE or Safari < 9.

**Comment by harshavardhana** [comment]
Ping @rushenn ..

**Comment by rushenn** [comment]
Thank you gitjeff05 

@bugs181: Fixed the issue using a polyfill as @gitjeff05 mentioned. Can you please merge the changes from branch https://github.com/rushenn/minio/tree/objectassign-polyfill and let us know the outcome?

**Comment by harshavardhana** [comment]
@bugs181 @gitjeff05 - to run a local test server navigate to `browser` directory. You can do 

```
npm run dev
```

**Comment by harshavardhana** [comment]
Fixed by #3884 - closing this bug as fixed - please re-open if you see problems @bugs181 @gitjeff05  - note browser assets are not yet updated. Until then you can test the changes with `npm run dev` in the `browser` folder.

**Comment by minherz** [comment]
The same problem (with different error log) happens in IE11.
On launching minio Web UI, the screen is stuck in launching animation and does not get to login.
The following error is displayed in console log:
```
SCRIPT438: Object doesn't support property or method 'assign'
index_bundle-2017-02-02T11-00-00Z.js (30,27164)
```

**Comment by krishnasrinivas** [comment]
@minherz we'll take a look.

**Comment by bugs181** [comment]
I can confirm that this fixed the issue for me. I apologize for the delay.
