### ISSUE TITLE
Multipart upload throwing error in 2.2.3 release

### ISSUE THREAD

**Issue by eldhosejohn** [minio/minio#4572]
In the latest release 2.2.3, the s3 multipart upload is throwing error. However this is working perfectly in 2.2.2 release

## Expected Behavior

Direct upload to S3.

## Current Behavior

AttributeError: 'PartMetadata' object has no attribute 'md5hasher'

see the logs

    s3Client.put_object(s3_bucket, s3_key, file_data, file_stat.st_size, content_type=content_type)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/minio/api.py", line 897, in put_object
    data, length, metadata=metadata)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/minio/api.py", line 1665, in _stream_put_object
    md5_hex = part_metadata.md5hasher.hexdigest()
AttributeError: 'PartMetadata' object has no attribute 'md5hasher'

## Steps to Reproduce (for bugs)

s3_key=''
file_locn='file.csv'
s3Client = Minio('s3.amazonaws.com',
                 access_key=AWS_ACCESS_KEY,
                 secret_key=AWS_SECRET_ACCESS_KEY,
                 secure=True)
file_stat = os.stat(file_locn)
file_data = open(file_locn, 'rb')
s3Client.put_object(s3_bucket, s3_key, file_data, file_stat.st_size, content_type='application/csv')

## Your Environment

* Version used (`minio version`): 2.2.3
* Environment name and version (e.g. nginx 1.9.1): Python 2.7
* Server type and version: Amazon Linux
* Operating System and version (`uname -a`): Linux
* Link to your project: Private

**Comment by krisis** [comment]
@eldhosejohn Could you open this issue in https://github.com/minio/minio-py/ repository? This repo is for the minio server.

**Comment by eldhosejohn** [comment]
got it, closing the issue.
